### ISSUE TITLE
Parallel current does not diverge/converge gracefully

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#127] opened 2017-08-02 21:47 UTC
@samreid This issue has varying degrees of expression, depending on the number of "current splits" created and the current through the wires. A simple setup with 4 splits is shown below:

<img width="1124" alt="screen shot 2017-08-02 at 3 30 06 pm" src="https://user-images.githubusercontent.com/5863899/28895906-7d140724-7797-11e7-9bd3-16094911555c.png">

Enabling current with this setup reveals gaps that form where the current converges. Keep in mind that the lifetime of these gaps is different depending on the difference in current before and after the convergence:
![cckdc06](https://user-images.githubusercontent.com/5863899/28896033-0e8e51c8-7798-11e7-94b9-7c23daf9c86e.gif)

Here's a more fun extreme case:
![cckdc08](https://user-images.githubusercontent.com/5863899/28896398-8be90cc0-7799-11e7-81a6-a998283f5ca9.gif)

Similarly, where the current is diverging, you can occasionally see electrons/arrows move *backwards* to fill in gaps. This is rarer and harder to see with the prescribed setup. Watch the top wire, and don't confuse the gif loop as the backwards motion!
![cckdc07](https://user-images.githubusercontent.com/5863899/28896203-b1d2a1fe-7798-11e7-809a-a2c9385f9ad1.gif)

This hardly makes sense to me, but I'm not an expert in circuits.

Seen on macOS 10.12.6 Chrome. For phetsims/QA/issues/33. @arouinfar said she would talk about how to tackle this at design meeting.

URL: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.135/circuit-construction-kit-dc_en.html
Version: 1.0.0-dev.135 2017-08-02 19:46:43 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36
Language: en-US
Window: 1920x1012
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"0e3d5567","branch":"master"},"babel":{"sha":"51a4bd3b","branch":"master"},"brand":{"sha":"b630f897","branch":"master"},"chipper":{"sha":"6829432d","branch":"master"},"circuit-construction-kit-common":{"sha":"ee9efcbe","branch":"master"},"circuit-construction-kit-dc":{"sha":"5e5b0c9f","branch":"master"},"dot":{"sha":"f7d9de8b","branch":"master"},"joist":{"sha":"8a235835","branch":"master"},"kite":{"sha":"41ac3b7a","branch":"master"},"phet-core":{"sha":"d8bec6c1","branch":"master"},"phetcommon":{"sha":"7ec5d299","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"9f5612d2","branch":"master"},"scenery-phet":{"sha":"23839a28","branch":"master"},"sherpa":{"sha":"be8e800b","branch":"master"},"sun":{"sha":"a56ba571","branch":"master"},"tandem":{"sha":"29cd4f63","branch":"master"},"twixt":{"sha":"3ca102d0","branch":"master"}}

**Comment by phet-steele** [comment] 2017-08-02 21:54
Here is this case where the electrons do not un-bunch until entering a wire:
![cckdc09](https://user-images.githubusercontent.com/5863899/28896721-d531c3ee-779a-11e7-872e-247001efba6a.gif)

**Comment by phet-steele** [comment] 2017-08-02 22:14
An example where backwards motion is much more obvious. Watch the wire attached to the resistor.

![cckdc10](https://user-images.githubusercontent.com/5863899/28897356-98b5f5cc-779d-11e7-9ce2-4c46fee8a054.gif)

**Comment by samreid** [comment] 2017-08-03 17:28
@phet-steele can you please characterize the behavior in the Java version?  Does it exhibit the same behavior?

**Comment by phet-steele** [comment] 2017-08-03 18:03
@samreid biggest difference I see is that electrons don't travel backwards to fill the gap:
![cckdc11](https://user-images.githubusercontent.com/5863899/28935888-263200d0-7843-11e7-8120-e827da0a3810.gif)

Electrons still bunch in batteries and resistors and such:
![cckdc12](https://user-images.githubusercontent.com/5863899/28936036-aa001082-7843-11e7-988e-10e2d08829f0.gif)

**Comment by samreid** [comment] 2017-08-03 21:30
@kathy-phet said look into it, but it may not warrant a significant or expensive fix.

**Comment by samreid** [comment] 2017-08-04 02:01
I'm seeing electrons go backwards sometimes too.  If I add this code, charges will never slow down, they will only speed up:

```js
        if (!sameDirectionAsCurrent){
          return;
        }
```

It seems OK in brief testing, I'm not sure if we need to make it possible for charges to slow down.

**Comment by samreid** [comment] 2017-08-04 02:04
Part of the problem is that charges do not remember their position before being updated, so it is currently not possible to make sure they do not travel backwards.

**Comment by samreid** [comment] 2017-08-04 02:12
I made a change so that charges can only speed up from postprocessing equalization, and never slow down or reverse.  I published it here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.137/circuit-construction-kit-dc_en.html

@phet-steele and @arouinfar please let me know if that is a good solution, or if I need to reopen investigation on slowing down charges (and making sure they do not reverse).

**Comment by phet-steele** [comment] 2017-08-04 16:36
- Why I've been told we won't be fixing the gap: It helps users track electrons and see that charge is conserved. Not going to change it.

- The backwards movement, however, is quite fixed @samreid, thanks! Fixed in the version linked directly above.

- One last thing that I don't think has been discussed: what about the electrons remaining bunched in fixed length components? Electrons don't appear to redistribute until they enter a wire. @arouinfar @samreid, please refer to  https://github.com/phetsims/circuit-construction-kit-dc/issues/127#issuecomment-319809924 and https://github.com/phetsims/circuit-construction-kit-dc/issues/127#issuecomment-319813958 to see this clearly.

**Comment by arouinfar** [comment] 2017-08-04 16:40
@samreid I haven't been able to spot any backwards movement in dev.137. @phet-steele is correct, we didn't discuss current redistribution in fixed-length components, but I think it would be nice to treat all components the same. @samreid would it be possible/reasonable to redistribute the electrons in fixed-length components too?

**Comment by samreid** [comment] 2017-08-04 16:42
> Electrons don't appear to redistribute until they enter a wire.

I believe the explanation for this is that the current strategy 

* only equalizes electrons that are within a single component (it does not look beyond the edges of the component to determine what electrons are "nearby")
* only equalizes the position of electrons between other electrons (within that component),  so the leading electron in a battery won't have its speed adjusted.  

We could investigate the following:
1. look beyond the edge of a component to determine location of neighbors.  This would increase complexity a little bit, and decrease performance a little bit and we would need to decide how to deal with the current directionality in adjacent component (I think)
2. allow adjusting the speed of electrons that are not between other electrons--say, if an electron is halfway across a battery and there is nothing ahead of it, we could increase its speed a bit

@arouinfar would you like to investigate possibilities like these before 1.0?

**Comment by samreid** [comment] 2017-08-04 16:43
> I think it would be nice to treat all components the same

They all use the same code but they exhibit different behavior because the wires can be much longer than the batteries and resistors, and hence there are more opportunities for electrons to be "between their neighbors in that circuit element".

**Comment by arouinfar** [comment] 2017-08-04 17:20
> They all use the same code but they exhibit different behavior because the wires can be much longer than the batteries and resistors, and hence there are more opportunities for electrons to be "between their neighbors in that circuit element".

Oh, that makes sense. Thanks for clarifying @samreid. 

1. How much of a performance hit would this be? A few fps? Dealing with current directionality in the adjacent component also sounds (potentially) complicated.

2. This sounds a bit more straightforward (at least to a layman like me), so maybe spend a little time looking into this?

@samreid I'd recommend that you look into whichever option you're more optimistic about for 1.0, but I don't think it warrants a significant time expenditure.

**Comment by samreid** [comment] 2017-08-04 18:46
> How much of a performance hit would this be? A few fps? 

It could be an additional ~1% CPU and garbage generation during charge animation.

**Comment by samreid** [comment] 2017-08-04 18:54
The simplest implementation to address (2) seems like it could lead to speeding up and slowing down of electrons as they pass through series elements.

**Comment by samreid** [comment] 2017-08-06 15:21
This strategy seems correct, but none too efficient!

```js
      // (1) choose 3 circuit elements.
      // * The one connected to the startVertex (but not charge.circuitElement) that has the closest electron to startVertex
      // * charge.circuitElement
      // * The one connected to the endVertex (but not charge.circuitElement) that has the closest electron to endVertex

      // (2) Order them from back to front--these define a new coordinate frame and can be used to sort the distances

      // (3) Choose the neighboring electrons using sorting indices--note the closest electrons may be in different circuit
      // elements, but since we have a relative coordinate
```

**Comment by kathy-phet** [comment] 2017-08-06 15:43
Maybe we should just stick with the original for v1.0 since there haven't been complaints.

Kathy

Sent from my iPhone

On Aug 6, 2017, at 9:21 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


This strategy seems correct, but none too efficient!

      // (1) choose 3 circuit elements.
      // * The one connected to the startVertex (but not charge.circuitElement) that has the closest electron to startVertex
      // * charge.circuitElement
      // * The one connected to the endVertex (but not charge.circuitElement) that has the closest electron to endVertex

      // (2) Order them from back to front--these define a new coordinate frame and can be used to sort the distances

      // (3) Choose the neighboring electrons using sorting indices--note the closest electrons may be in different circuit
      // elements, but since we have a relative coordinate

**Comment by samreid** [comment] 2017-08-06 19:07
> Maybe we should just stick with the original for v1.0 since there haven't been complaints.

I'm OK with that, let's see what else comes up in testing.  Another possibility may be to write an algorithm that finds the distance to the nearest electron in each direction, then use that to equalize the distances.  It may take 4 hours for initial implementation.

**Comment by kathy-phet** [comment] 2017-08-06 19:25
I'm a bit worried about unintended consequences from any other models. Right now the behavior is relatively easy to understand why it might show that type of representation given the limitations of showing each electron as a big ball and not wanting to change its speed ... e.g. Current is constant in any element. I think other implementations might be harder to rationalize why things are speeding up or slowing down when the current is the same along an element. Given the nature of the circuit that showed the issue, I cannot think of how I would visually change the behavior in a way that would not cause other complications, none the less model it. If we had many more smaller elections it would not be perceptible but our elections are big and take up substantial space.

Kathy

Sent from my iPhone

On Aug 6, 2017, at 1:07 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe we should just stick with the original for v1.0 since there haven't been complaints.

I'm OK with that, let's see what else comes up in testing. Another possibility may be to write an algorithm that finds the distance to the nearest electron in each direction, then use that to equalize the distances. It may take 4 hours for initial implementation.

**Comment by kathy-phet** [comment] 2017-08-06 19:36
Obviously electrons not elections .... uggg autocorrect.

Sent from my iPhone

On Aug 6, 2017, at 1:25 PM, Kathy Perkins <katherine.perkins@Colorado.EDU<mailto:katherine.perkins@Colorado.EDU>> wrote:

I'm a bit worried about unintended consequences from any other models. Right now the behavior is relatively easy to understand why it might show that type of representation given the limitations of showing each electron as a big ball and not wanting to change its speed ... e.g. Current is constant in any element. I think other implementations might be harder to rationalize why things are speeding up or slowing down when the current is the same along an element. Given the nature of the circuit that showed the issue, I cannot think of how I would visually change the behavior in a way that would not cause other complications, none the less model it. If we had many more smaller elections it would not be perceptible but our elections are big and take up substantial space.

Kathy

Sent from my iPhone

On Aug 6, 2017, at 1:07 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe we should just stick with the original for v1.0 since there haven't been complaints.

I'm OK with that, let's see what else comes up in testing. Another possibility may be to write an algorithm that finds the distance to the nearest electron in each direction, then use that to equalize the distances. It may take 4 hours for initial implementation.

**Comment by samreid** [comment] 2017-08-06 20:02
Understood, unassigning for now.

**Comment by arouinfar** [comment] 2017-08-09 19:11
After further discussion with @kathy-phet we've decided to leave things as-is. @samreid was able to address the backward-moving current carriers, which was the most problematic part of this issue. Closing as `wont-fix`.

**Closed by arouinfar** 2017-08-09 19:11 UTC
Labels: design:general, type:bug
