### ISSUE TITLE
[iPad2] Safari sometimes refreshes tab

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-dc#141] opened 2017-08-18 00:48 UTC
For https://github.com/phetsims/QA/issues/33. Most likely this is a Safari issue, rather than a sim issue, but opening so @samreid and @jonathanolson can take a look. When it comes to iPad2 performance, I'm much more concerned with #140.

With dev.135 running in one tab, opening another sim in a 2nd Safari tab and then switching back to the CCK tab can cause the browser tab to refresh. Initially, I thought the circuit needed to a bit beefy (high voltage and a few parallel branches like the one below) to cause the tab to crash, but but that isn't always the case.
 
![file_000 1](https://user-images.githubusercontent.com/8419308/29439392-79983338-837a-11e7-9732-d3582a085f5a.png)

One way to reproduce:
1. Open dev.135 and build a simple single battery + bulb circuit. 
2. Crank voltage up to 120 V.
3. Open dev.153 in a 2nd Safari tab, and build the same circuit.
4. Switch back to dev.135 tab, and it'll refresh.

Another method (slightly less consistent):
1. Repeat steps 1-2 above.
2. Open ESPB 1.1.5 in a 2nd Safari tab and choose Intro.
3. Drag skater onto track and turn on all checkboxes
4. Switch back to CCK dev.135 tab, and it'll refresh.

Once I was able to get ESPB to refresh instead of CCK. I don't remember the exact method but something along the lines of:
1. Build single battery + bulb circuit in dev.135
2. Open ESPB 1.1.5 in a 2nd Safari tab and choose Intro.
3. Drag skater onto track and turn on all checkboxes
4. Switch back to CCK and it seems ok. Make the circuit more complicated (adding more bulbs and increasing voltage helps).
5. Switch back to ESPB and it refreshed. 

Couldn't find a convenient way to get the text off the iPad, so I suppose a screenshot'll do.
![file_000](https://user-images.githubusercontent.com/8419308/29429596-7e3760b6-834e-11e7-8912-d85c56932b29.png)

**Comment by samreid** [comment] 2017-08-18 20:25
@jonathanolson and I discovered this is a widespread problem, there are many sites dedicated to discussing this problem.  We also ran the following test on iPad2: load disneyland's homepage on one tab and disneyworld's homepage on the other tab, then tab to disneyland and back to disneyworld.  When we did this, disneyworld reloaded itself.  So the problem is not isolated to PhET sims, and even would be a problem for even the lowest-memory PhET sim, if the user loads another tab that uses a lot of memory.  

Browsers think they can reload tabs when necessary and get them back in the desired state-- @jonathanolson proposed using localstorage or sessionstorage to store the state of the simulation so if this happens the sim will still come up the way you left it, even if the browser refreshes itself.

**Comment by kathy-phet** [comment] 2017-08-18 23:08
Thanks for looking into this. I don't think we should pursue saving the state, since that seems tantamount to adding PhET-iO to the sim ... at least in my naive understanding.

**Comment by samreid** [comment] 2017-08-19 00:11
> Thanks for looking into this. I don't think we should pursue saving the state, since that seems tantamount to adding PhET-iO to the sim ... at least in my naive understanding.

I think it would be best to publish CCK-DC 1.0.0 without addressing this problem, but one day we may wish to investigate state save/load to address this issue in general.  The straightforward way to add state saving would be to use the PhET-iO implementation.  But we could also implement a separate save implementation, or find a way to separate the save/load part from PhET-iO, but still have PhET-iO leverage it.

@kathy-phet please advise.

**Comment by jonathanolson** [comment] 2017-08-19 01:55
Created https://github.com/phetsims/joist/issues/437 for the general issue, and I have a proposed solution for the general case (if a sim is able to save and load its state).

@samreid, would save/load of state be realistic for this simulation (to solve this problem)? Otherwise, I don't see a way to fix it, since low-memory tabs get reloaded also.

**Comment by kathy-phet** [comment] 2017-08-19 04:24
Thx, Sam. I agree with publishing 1.0.0 without addressing this issue.

It's not a priority to do save/load right now outside of offering it to PhET-iO clients/app when we get to that.

Sent from my iPhone

On Aug 18, 2017, at 6:11 PM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for looking into this. I don't think we should pursue saving the state, since that seems tantamount to adding PhET-iO to the sim ... at least in my naive understanding.

I think it would be best to publish CCK-DC 1.0.0 without addressing this problem, but one day we may wish to investigate state save/load to address this issue in general. The straightforward way to add state saving would be to use the PhET-iO implementation. But we could also implement a separate save implementation, or find a way to separate the save/load part from PhET-iO, but still have PhET-iO leverage it.

@kathy-phet<https://github.com/kathy-phet> please advise.

**Comment by samreid** [comment] 2017-08-19 14:43
OK thanks, let's close this issue, then we can reopen it if/when we decide to work on https://github.com/phetsims/joist/issues/437

**Closed by samreid** 2017-08-19 14:43 UTC
Labels: type:performance
