### ISSUE TITLE
Wire is aliased on Firefox and iPad2

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#111] opened 2017-07-26 20:49 UTC
Discovered in #109, the wire is aliased in Firefox

![image](https://user-images.githubusercontent.com/679486/28643009-9e44ebba-7211-11e7-9791-e1619f94ca25.png)

**Comment by samreid** [comment] 2017-07-26 21:43
@jonathanolson anything we can do about this?  It is rendered with toDataURLNodeSynchronous then Image/webgl.

**Comment by jonathanolson** [comment] 2017-07-26 21:50
Theoretically, adding back in some vertical padding for the wire may help (keeping the lack of padding at the ends).

Will check for local reproduction.

**Comment by jonathanolson** [comment] 2017-07-27 16:40
Cannot reproduce locally:

![screen shot 2017-07-27 at 10 39 45 am](https://user-images.githubusercontent.com/480878/28681796-f5f0f3da-72b7-11e7-9c38-c2d40d05826d.png)

What device did this happen on?

**Comment by samreid** [comment] 2017-07-27 16:43
The screenshot in the top comment is from Firefox on my MBP retina display:
![image](https://user-images.githubusercontent.com/679486/28681922-62b9e382-72b8-11e7-96f5-3c388feea3d1.png)

**Comment by jonathanolson** [comment] 2017-07-27 18:11
The retina part may be relevant. Collaborating on this may help.

**Comment by samreid** [comment] 2017-07-28 03:23
Same app, no problem.  

![image](https://user-images.githubusercontent.com/679486/28701224-e0c6e76c-7311-11e7-8c23-32633852834d.png)

Let me see if it is a problem in the built version.

**Comment by samreid** [comment] 2017-07-28 03:25
It looks equally great in the published version.  Not sure what was wrong in my original post.  I tried ?webgl=false and it also looked good.  Closing.

**Comment by samreid** [comment] 2017-07-31 22:04
@phet-steele saw this again on iPad2

**Comment by jonathanolson** [comment] 2017-07-31 23:15
I believe @phet-steele said this looked better on his side. @samreid can you confirm?

**Comment by samreid** [comment] 2017-08-01 01:02
Looks great, thanks!  @jonathanolson anything else to do for this issue?

**Comment by jonathanolson** [comment] 2017-08-01 01:17
Nope, closing.

**Closed by jonathanolson** 2017-08-01 01:17 UTC
