### ISSUE TITLE
TypeError from phet-io fuzz test

### ISSUE THREAD

**Issue by zepumph** [phetsims/circuit-construction-kit-dc#39] opened 2017-05-03 16:33 UTC
```
phetio.js?bust=1493828297449:478 Uncaught TypeError: Cannot read property 'typeName' of null
    at Object.removeInstance (phetio.js?bust=1493828297449:478)
    at Object.removeInstance (phetio.js?bust=1493828297449:60)
    at Tandem.removeInstance (Tandem.js?bust=1493828297449:142)
    at ResistorNode.dispose (Node.js?bust=1493828297449:4980)
    at ResistorNode.dispose (CircuitElementNode.js?bust=1493828297449:100)
    at ResistorNode.dispose (FixedLengthCircuitElementNode.js?bust=1493828297449:300)
    at ResistorNode.dispose (ResistorNode.js?bust=1493828297449:159)
    at Array.<anonymous> (CircuitNode.js?bust=1493828297449:123)
    at ObservableArray._fireItemRemoved (ObservableArray.js?bust=1493828297449:159)
    at ObservableArray.remove (ObservableArray.js?bust=1493828297449:199)

**Comment by samreid** [comment] 2017-05-03 21:25
I fixed several phet-io things this afternoon and cannot reproduce this problem.  @zepumph can you test if it is fixed now?

**Comment by zepumph** [comment] 2017-05-03 22:58
I fuzzed for a long time, both in phet and phet-io brand, but I only got the error from #40, and not this one. I would say safe to close.

**Closed** 2017-05-03 22:58 UTC
