### ISSUE TITLE
Quick zooming sometimes changes the layout bounds

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit-dc#99] opened 2017-07-21 21:50 UTC
@samreid it looks like if I very quickly press zoom in and zoom out in sequence (just the one iteration), the layout bounds do not encompass the entire screen. This is evidenced by two things:

- Tools cannot be dragged to the edges of the screen. Not letting the sensors go anywhere in the play area limits the ability for sensors to measure components around the edges of the screen.
- The cut button can become detached from components that are around the edges of the screen, simply because the cut button cannot travel beyond the layout bounds.

<img width="355" alt="screen shot 2017-07-21 at 3 49 07 pm" src="https://user-images.githubusercontent.com/5863899/28483794-37ddb28c-6e2c-11e7-9fab-a9491e01f3e4.png">

Now this doesn't happen every time, this issue is really hard to pin down. Don't be discouraged by difficulty reproducing.

Verified on http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.87/circuit-construction-kit-dc_en.html with macOS 10.12.5 Chrome and iOS 9.3.5 & 10.3.2. For phetsims/QA#26.

**Comment by samreid** [comment] 2017-07-23 21:27
I wasn't able to reproduce this problem on Mac, even after slowing down time.  On iPad I tested for 2-3 minutes and saw an issue once where the scissors were able to move out of the bounds of the screen.

**Comment by samreid** [comment] 2017-07-25 04:15
@phet-steele I'd love some more guidance on this.  Do you think it has to do with changing the zoom level while the zoom is changing?

@jonathanolson I'd love your help looking into this if and when you have time.

**Comment by samreid** [comment] 2017-07-25 18:38
@jonathanolson identified an incorrect parameter in the tween initialization which may have caused this problem.  I committed a fix above.

**Comment by samreid** [comment] 2017-07-25 18:41
New version is published here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.104/circuit-construction-kit-dc_en.html

@phet-steele can you please test and see if the problem is still there?

**Comment by samreid** [comment] 2017-07-25 19:49
@jonathanolson and I fixed an order dependency in the scaling callbacks and published a dev version here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.105/circuit-construction-kit-dc_en.html

@phet-steele can you please test it out?

**Comment by phet-steele** [comment] 2017-07-27 16:12
> @phet-steele can you please test it out?

I can't reproduce in http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.111/circuit-construction-kit-dc_en.html anymore, so maybe that commit did it?

**Comment by phet-steele** [comment] 2017-07-28 19:54
Ack, @samreid I don't know if this is new or not, but now layout bounds are incorrect UNTIL I zoom. So right from sim opening, I drag out a sensor and am not allowed to drag out of dev bounds. Once I zoom out then in, everything is fine. Just tried this on master.

**Comment by samreid** [comment] 2017-07-30 14:08
I'll track this in new issue #123

**Closed by samreid** 2017-07-30 14:08 UTC
Labels: type:bug
