### ISSUE TITLE
Schematic component dimensions are wrong

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-dc#122] opened 2017-07-28 22:27 UTC
When dragging out a component in schematic mode, its dimensions are wrong.  this was on edge but maybe it happens everywhere

![image](https://user-images.githubusercontent.com/679486/28738598-39f7fcbc-73a9-11e7-9960-cf227ddc9eee.png)

**Comment by samreid** [comment] 2017-07-28 22:28
Or maybe they are all just wrong now?

**Comment by samreid** [comment] 2017-07-30 14:14
Probably introduced after I added caching to fix a spritesheet memory leak.

**Comment by samreid** [comment] 2017-07-31 15:24
Proposed fix is here: http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.122/circuit-construction-kit-dc_en.html

@arouinfar can you please take a look?

**Comment by arouinfar** [comment] 2017-07-31 16:56
> When dragging out a component in schematic mode, its dimensions are wrong. this was on edge but maybe it happens everywhere

@samreid I wasn't able to reproduce this in dev.121 in Mac/Chrome or Win10/Edge, so I'm not sure how to verify the fix in dev.122. @phet-steele have you observed this behavior?

**Comment by samreid** [comment] 2017-07-31 17:40
To see the buggy version, use any browser and launch http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.121/circuit-construction-kit-dc_en.html

Then switch to schematic and drag out a dog.  You should see something like this:

![image](https://user-images.githubusercontent.com/679486/28790133-181a2bd6-75e5-11e7-99cf-1271a01017c0.png)

**Comment by arouinfar** [comment] 2017-07-31 17:44
Thanks @samreid! I had been testing the standard components, not the Grab Bag items. I cannot reproduce the issue in dev.122. Closing.

**Closed by arouinfar** 2017-07-31 17:44 UTC
Labels: status:ready-to-test
