### ISSUE TITLE
CT running lint-all task

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/circuit-construction-kit-dc#177] opened 2019-01-24 00:01 UTC
```
circuit-construction-kit-dc : build : phet
Failure to grunt snapshot-1548281897096/circuit-construction-kit-dc:
Running "lint-all" task

Running "report-media" task
>> missing-file: circuit-construction-kit-common/images/ammeter_probe.png
Fatal error: There is an issue with the licenses for media types.


Approximately 1/23/2019, 3:18:17 PM
```

**Comment by pixelzoom** [comment] 2019-01-24 03:49
Duplicate of https://github.com/phetsims/circuit-construction-kit-black-box-study/issues/69, closing.

**Closed by pixelzoom** 2019-01-24 03:49 UTC
Labels: type:automated-testing
