### ISSUE TITLE
User question: phase incorrect for RLC circuits

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/circuit-construction-kit-dc#2] opened 2016-10-06 19:19 UTC
I would like to point out one Error in the Simulation

https://phet.colorado.edu/en/simulation/legacy/circuit-construction-kit-ac

That when using the Circuit Elements R, L and C with AC source and when connected with the CRO its displayed wave forms V & I are not according to the principles of Phase diagram like
1. For R=Resistor
   Both  V=Voltage  & =Current AC wave form should be in Phase. (which are not)
2. For L=Inductor

The V=voltage  should Lead the I=Current by 90 degrees
1. For C=Capacitor
   The     V=Voltage lags behind the current by 90 degrees

So kindly make these corrections an if you do than please send me the corrected simulation link so that I could demonstrate to the students in the Class.

**Comment by samreid** [comment] 2017-01-27 20:24
I recall conversation about this, sometime in the last 6 months.  I should review email/unfuddle.  If I can't find anything, perhaps @ariel-phet or @phet-steele will recall something.

**Comment by samreid** [comment] 2017-03-08 22:25
@arouinfar can you look into this?  Did you come across anything like this in unfuddle?

**Comment by arouinfar** [comment] 2017-06-07 20:47
@samreid I found the corresponding Unuddle [Ticket](https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3727), which has been resolved. @ariel-phet responded: 
> Hey Oliver,
I looked into this, it appears the issue is the way the user has hooked up the leads from the voltage chart tool. If he reverses the leads he will see the proper behavior (as shown in the attached screenshot). As seen in the screenshot, the Voltage now properly leads the current by 90 degrees in phase. 
When the leads are flipped, there is a 180 degree phase shift (thus why in his pictures the Voltage *lags* the current by 90 degrees in phases instead of leading it by 90 degrees as the user expects).
Ariel

Looks like this was a user error, rather than a sim error. There doesn't appear to be anything that needs to be done here, so I'll go ahead and close the issue.

**Closed by arouinfar** 2017-06-07 20:47 UTC
Labels: cck-dc:1.1, type:question
