### ISSUE TITLE
CCK DC Suite - Publish 1.3 with PhET-iO

### ISSUE THREAD

**Issue by markgammon** [phetsims/circuit-construction-kit-dc#193] opened 2021-11-16 23:25 UTC
Publish with the latest PhET-iO Studio code base and upgrades. 

See milestone for remaining issues
https://github.com/phetsims/circuit-construction-kit-common/milestone/5

**Comment by samreid** [comment] 2023-02-23 22:57
Since the BLL RC turned out awkward, I'll paste the steps for the CCK RC here (in case something goes wrong). I confirmed we are publishing 1.3.  Then I pulled all repos and made sure I was in master for all repos. Then I started VPN and ran `grunt rc --brands=phet,phet-io --branch=1.3`.  I spot checked 2 dependency SHAs and they looked accurate.  I tested PhET brand and Studio, and it worked well.  Studio alt keys with stationary mouse are working great in the local test: https://github.com/phetsims/studio/issues/295

<details>

```
~/apache-document-root/main/circuit-construction-kit-dc$ grunt rc --brands=phet,phet-io --branch=1.3
Running "rc" task
(Forwarding task to perennial)
Running "rc" task
Release branch 1.3 does not exist. Create it? [y/N]?y
info: Setting the release branch version to rc.0 so it will auto-increment to rc.1 for the first RC deployment
info: git checkout -b 1.3 on circuit-construction-kit-dc
info: Setting version from package.json for circuit-construction-kit-dc to 1.3.0-rc.0
info: git add package.json on circuit-construction-kit-dc
info: git commit on circuit-construction-kit-dc with message:
Bumping version to 1.3.0-rc.0
info: git push on circuit-construction-kit-dc to 1.3
info: npm update on circuit-construction-kit-dc
info: npm update on chipper
info: npm update on perennial-alias
info: building circuit-construction-kit-dc
info: Copying ../circuit-construction-kit-dc/build/phet/dependencies.json to ../circuit-construction-kit-dc/dependencies.json
info: git add dependencies.json on circuit-construction-kit-dc
info: git commit on circuit-construction-kit-dc with message:
updated dependencies.json for version 1.3.0-rc.0
info: git push on circuit-construction-kit-dc to 1.3
info: git checkout master on circuit-construction-kit-dc
info: Setting version from package.json for circuit-construction-kit-dc to 1.4.0-dev.0
info: git add package.json on circuit-construction-kit-dc
info: git commit on circuit-construction-kit-dc with message:
Bumping version to 1.4.0-dev.0
info: Updating HTML for circuit-construction-kit-dc with the new version strings
info: git add circuit-construction-kit-dc_en.html on circuit-construction-kit-dc
info: git commit on circuit-construction-kit-dc with message:
Bumping dev HTML with new version
info: git push on circuit-construction-kit-dc to master
info: git checkout 1.3 on circuit-construction-kit-dc
info: git checkout 1.3 on circuit-construction-kit-dc
info: checking out shas for circuit-construction-kit-dc 1.3
info: git checkout 1.3 on circuit-construction-kit-dc
info: git pull on circuit-construction-kit-dc
info: getting dependencies.json for circuit-construction-kit-dc
info: checking out dependencies for circuit-construction-kit-dc
info: git checkout c13a8c7741d95fbd8e37619c66ebcca8686dffe7 on assert
info: git checkout 66db00a05d04ea5b60ad50d874b87e7ba7923dfb on axon
info: git checkout 5c4e6bc0b4e2809545b968e04c24bd2ae206c99a on bamboo
info: git checkout c73b827b08b394ced9442e88e5ef33755f50ad73 on brand
info: git checkout ee0967fa0bd1b8474bef0737bb098ca8a6dde2f7 on chipper
info: git checkout 374c935a1bc7d89588d39a2922a58b862ba42c36 on circuit-construction-kit-common
info: git checkout a2267c92639bc755052aa50abd5b84e60e90b057 on dot
info: git checkout d40ca0608636bbf4b35dde3796b1c32c2765d65f on griddle
info: git checkout 22c26506a7fcf323c57038f05f6df6fd85a45511 on joist
info: git checkout 59e334a621dfd4b3eaaa849c578b0cd44a252ca1 on kite
info: git checkout 41d6196c2b47adef62fa1251a13382bbd8502286 on perennial-alias
info: git checkout 3e4b333e1ca4b59f4ab9942bd2f177725989acb0 on phet-core
info: git checkout 197b6f3031a032fd8b608d1bf07aeaf3a47ac17b on phet-io
info: git checkout 169cb0e0892e0cf97b221ca05acf06a13a5a7e90 on phet-io-sim-specific
info: git checkout 8eb004b1c478f59619ca84d8a334446df468645d on phet-io-wrappers
info: git checkout b1f8935b6c41b7c62fcf6c0d30d4b92280552226 on phetcommon
info: git checkout 5b3084a2ea029dec575e5dd00752b4013056c13b on phetmarks
info: git checkout ff7b4489cd1ab78b08f1e3a38e89c6d89abcd56a on query-string-machine
info: git checkout 5d3c7828abb2da78f80144c425b687e117d046b6 on scenery
info: git checkout ea4d8f6c92e7b61ffe34779b79698b0910a10662 on scenery-phet
info: git checkout da87d8d05efe43d7534545bd66021c9b2649f269 on sherpa
info: git checkout 2ac715ee72a50aa757742a5cb5f533095dd77512 on studio
info: git checkout 6c5f9d97f3cbe083681e7d2d820463466aeee0b6 on sun
info: git checkout b2005d822973ab90f8c515788f4828727576f433 on tambo
info: git checkout 02a8c16c16a4c5ef5171cf63f33d247b0f54fe81 on tandem
info: git checkout 5752086d1b09bad23beb77c8505f7073b993d1a6 on twixt
info: git checkout 063730ba839fc44f570179d6b712ddcb73232617 on utterance-queue
info: npm update on circuit-construction-kit-dc
info: npm update on chipper
info: npm update on perennial-alias
info: running [[ -d "/data/web/htdocs/dev/html/circuit-construction-kit-dc/1.3.0-rc.1" ]] && echo exists || echo not remotely on bayes.colorado.edu
Deploy 1.3.0-rc.1 to bayes.colorado.edu [y/N]?y
info: Setting version from package.json for circuit-construction-kit-dc to 1.3.0-rc.1
info: git add package.json on circuit-construction-kit-dc
info: git commit on circuit-construction-kit-dc with message:
Bumping version to 1.3.0-rc.1
info: git push on circuit-construction-kit-dc to 1.3
info: npm update on circuit-construction-kit-dc
info: npm update on chipper
info: npm update on perennial-alias
info: building circuit-construction-kit-dc
Running "lint-all" task
[........................................] 100.00%

Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 1610ms
Building runnable repository (circuit-construction-kit-dc, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 1845ms
>> Production minification complete: 8327ms (2617791 bytes)
>> Debug minification complete: 0ms (24826450 bytes)
Building brand: phet-io
>> Webpack build complete: 1437ms
>> Production minification complete: 8013ms (2632308 bytes)
>> Debug minification complete: 8014ms (2939204 bytes)
No migration rules found at ../chipper/dist/js/phet-io-sim-specific/repos/circuit-construction-kit-dc/js/circuit-construction-kit-dc-migration-rules.js, no rules to be bundled with phet-io.js.
>> tsc complete: 7517ms
>> tsc complete: 7417ms
Message from sim: an attempt was made to set the output level for a sound category on an uninitialized sound manager, ignoring

Done.

Please test the built version of circuit-construction-kit-dc.
Is it ready to deploy [y/N]?y
info: updating top-level dependencies.json for circuit-construction-kit-dc 1.3.0-rc.1 to branch 1.3
info: Copying ../circuit-construction-kit-dc/build/phet/dependencies.json to ../circuit-construction-kit-dc/dependencies.json
info: git add dependencies.json on circuit-construction-kit-dc
info: git commit on circuit-construction-kit-dc with message:
updated dependencies.json for 1.3.0-rc.1
info: git push on circuit-construction-kit-dc to 1.3
info: getting dependencies.json for circuit-construction-kit-dc
info: sending build request for circuit-construction-kit-dc 1.3.0-rc.1 with dependencies: {"comment":"# circuit-construction-kit-dc 1.3.0-rc.1 Thu Feb 23 2023 15:52:27 GMT-0700 (Mountain Standard Time)","assert":{"sha":"c13a8c7741d95fbd8e37619c66ebcca8686dffe7","branch":"HEAD"},"axon":{"sha":"66db00a05d04ea5b60ad50d874b87e7ba7923dfb","branch":"HEAD"},"bamboo":{"sha":"5c4e6bc0b4e2809545b968e04c24bd2ae206c99a","branch":"HEAD"},"brand":{"sha":"c73b827b08b394ced9442e88e5ef33755f50ad73","branch":"HEAD"},"chipper":{"sha":"ee0967fa0bd1b8474bef0737bb098ca8a6dde2f7","branch":"HEAD"},"circuit-construction-kit-common":{"sha":"374c935a1bc7d89588d39a2922a58b862ba42c36","branch":"HEAD"},"circuit-construction-kit-dc":{"sha":"2ff69c330c3002d4748f7fc311fbdb5515377b8e","branch":"1.3"},"dot":{"sha":"a2267c92639bc755052aa50abd5b84e60e90b057","branch":"HEAD"},"griddle":{"sha":"d40ca0608636bbf4b35dde3796b1c32c2765d65f","branch":"HEAD"},"joist":{"sha":"22c26506a7fcf323c57038f05f6df6fd85a45511","branch":"HEAD"},"kite":{"sha":"59e334a621dfd4b3eaaa849c578b0cd44a252ca1","branch":"HEAD"},"perennial-alias":{"sha":"41d6196c2b47adef62fa1251a13382bbd8502286","branch":"HEAD"},"phet-core":{"sha":"3e4b333e1ca4b59f4ab9942bd2f177725989acb0","branch":"HEAD"},"phet-io":{"sha":"197b6f3031a032fd8b608d1bf07aeaf3a47ac17b","branch":"HEAD"},"phet-io-sim-specific":{"sha":"169cb0e0892e0cf97b221ca05acf06a13a5a7e90","branch":"HEAD"},"phet-io-wrappers":{"sha":"8eb004b1c478f59619ca84d8a334446df468645d","branch":"HEAD"},"phetcommon":{"sha":"b1f8935b6c41b7c62fcf6c0d30d4b92280552226","branch":"HEAD"},"phetmarks":{"sha":"5b3084a2ea029dec575e5dd00752b4013056c13b","branch":"HEAD"},"query-string-machine":{"sha":"ff7b4489cd1ab78b08f1e3a38e89c6d89abcd56a","branch":"HEAD"},"scenery":{"sha":"5d3c7828abb2da78f80144c425b687e117d046b6","branch":"HEAD"},"scenery-phet":{"sha":"ea4d8f6c92e7b61ffe34779b79698b0910a10662","branch":"HEAD"},"sherpa":{"sha":"da87d8d05efe43d7534545bd66021c9b2649f269","branch":"HEAD"},"studio":{"sha":"2ac715ee72a50aa757742a5cb5f533095dd77512","branch":"HEAD"},"sun":{"sha":"6c5f9d97f3cbe083681e7d2d820463466aeee0b6","branch":"HEAD"},"tambo":{"sha":"b2005d822973ab90f8c515788f4828727576f433","branch":"HEAD"},"tandem":{"sha":"02a8c16c16a4c5ef5171cf63f33d247b0f54fe81","branch":"HEAD"},"twixt":{"sha":"5752086d1b09bad23beb77c8505f7073b993d1a6","branch":"HEAD"},"utterance-queue":{"sha":"063730ba839fc44f570179d6b712ddcb73232617","branch":"HEAD"}}
info: https://phet.colorado.edu/deploy-html-simulation
info: {"api":"2.0","dependencies":"{\"comment\":\"# circuit-construction-kit-dc 1.3.0-rc.1 Thu Feb 23 2023 15:52:27 GMT-0700 (Mountain Standard Time)\",\"assert\":{\"sha\":\"c13a8c7741d95fbd8e37619c66ebcca8686dffe7\",\"branch\":\"HEAD\"},\"axon\":{\"sha\":\"66db00a05d04ea5b60ad50d874b87e7ba7923dfb\",\"branch\":\"HEAD\"},\"bamboo\":{\"sha\":\"5c4e6bc0b4e2809545b968e04c24bd2ae206c99a\",\"branch\":\"HEAD\"},\"brand\":{\"sha\":\"c73b827b08b394ced9442e88e5ef33755f50ad73\",\"branch\":\"HEAD\"},\"chipper\":{\"sha\":\"ee0967fa0bd1b8474bef0737bb098ca8a6dde2f7\",\"branch\":\"HEAD\"},\"circuit-construction-kit-common\":{\"sha\":\"374c935a1bc7d89588d39a2922a58b862ba42c36\",\"branch\":\"HEAD\"},\"circuit-construction-kit-dc\":{\"sha\":\"2ff69c330c3002d4748f7fc311fbdb5515377b8e\",\"branch\":\"1.3\"},\"dot\":{\"sha\":\"a2267c92639bc755052aa50abd5b84e60e90b057\",\"branch\":\"HEAD\"},\"griddle\":{\"sha\":\"d40ca0608636bbf4b35dde3796b1c32c2765d65f\",\"branch\":\"HEAD\"},\"joist\":{\"sha\":\"22c26506a7fcf323c57038f05f6df6fd85a45511\",\"branch\":\"HEAD\"},\"kite\":{\"sha\":\"59e334a621dfd4b3eaaa849c578b0cd44a252ca1\",\"branch\":\"HEAD\"},\"perennial-alias\":{\"sha\":\"41d6196c2b47adef62fa1251a13382bbd8502286\",\"branch\":\"HEAD\"},\"phet-core\":{\"sha\":\"3e4b333e1ca4b59f4ab9942bd2f177725989acb0\",\"branch\":\"HEAD\"},\"phet-io\":{\"sha\":\"197b6f3031a032fd8b608d1bf07aeaf3a47ac17b\",\"branch\":\"HEAD\"},\"phet-io-sim-specific\":{\"sha\":\"169cb0e0892e0cf97b221ca05acf06a13a5a7e90\",\"branch\":\"HEAD\"},\"phet-io-wrappers\":{\"sha\":\"8eb004b1c478f59619ca84d8a334446df468645d\",\"branch\":\"HEAD\"},\"phetcommon\":{\"sha\":\"b1f8935b6c41b7c62fcf6c0d30d4b92280552226\",\"branch\":\"HEAD\"},\"phetmarks\":{\"sha\":\"5b3084a2ea029dec575e5dd00752b4013056c13b\",\"branch\":\"HEAD\"},\"query-string-machine\":{\"sha\":\"ff7b4489cd1ab78b08f1e3a38e89c6d89abcd56a\",\"branch\":\"HEAD\"},\"scenery\":{\"sha\":\"5d3c7828abb2da78f80144c425b687e117d046b6\",\"branch\":\"HEAD\"},\"scenery-phet\":{\"sha\":\"ea4d8f6c92e7b61ffe34779b79698b0910a10662\",\"branch\":\"HEAD\"},\"sherpa\":{\"sha\":\"da87d8d05efe43d7534545bd66021c9b2649f269\",\"branch\":\"HEAD\"},\"studio\":{\"sha\":\"2ac715ee72a50aa757742a5cb5f533095dd77512\",\"branch\":\"HEAD\"},\"sun\":{\"sha\":\"6c5f9d97f3cbe083681e7d2d820463466aeee0b6\",\"branch\":\"HEAD\"},\"tambo\":{\"sha\":\"b2005d822973ab90f8c515788f4828727576f433\",\"branch\":\"HEAD\"},\"tandem\":{\"sha\":\"02a8c16c16a4c5ef5171cf63f33d247b0f54fe81\",\"branch\":\"HEAD\"},\"twixt\":{\"sha\":\"5752086d1b09bad23beb77c8505f7073b993d1a6\",\"branch\":\"HEAD\"},\"utterance-queue\":{\"sha\":\"063730ba839fc44f570179d6b712ddcb73232617\",\"branch\":\"HEAD\"}}","simName":"circuit-construction-kit-dc","version":"1.3.0-rc.1","locales":["en"],"servers":["dev"],"brands":["phet","phet-io"],"branch":"1.3","authorizationCode":"REDACTED","email":"REDACTED"}
info: Build request sent successfully
info: checking out master for circuit-construction-kit-dc
info: getting dependencies.json for circuit-construction-kit-dc
info: git checkout master on assert
info: git checkout master on axon
info: git checkout master on bamboo
info: git checkout master on brand
info: git checkout master on chipper
info: git checkout master on circuit-construction-kit-common
info: git checkout master on circuit-construction-kit-dc
info: git checkout master on dot
info: git checkout master on griddle
info: git checkout master on joist
info: git checkout master on kite
info: git checkout master on perennial-alias
info: git checkout master on phet-core
info: git checkout master on phet-io
info: git checkout master on phet-io-sim-specific
info: git checkout master on phet-io-wrappers
info: git checkout master on phetcommon
info: git checkout master on phetmarks
info: git checkout master on query-string-machine
info: git checkout master on scenery
info: git checkout master on scenery-phet
info: git checkout master on sherpa
info: git checkout master on studio
info: git checkout master on sun
info: git checkout master on tambo
info: git checkout master on tandem
info: git checkout master on twixt
info: git checkout master on utterance-queue
info: npm update on circuit-construction-kit-dc
info: npm update on chipper
info: npm update on perennial-alias
Deployed: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-rc.1/phet/circuit-construction-kit-dc_en_phet.html
Deployed: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-rc.1/phet-io/
Please wait for the build-server to complete the deployment, and then test!

Done.

Done.

```

</details>

**Comment by samreid** [comment] 2023-03-08 19:49
Issues from RC.1 addressed.  Here is our list for cherry-picking:

```
https://github.com/phetsims/phet-io-sim-specific/commit/efbfbea32113677dfc6a28ee67d0134ed030fd3e
https://github.com/phetsims/phet-io-sim-specific/commit/264769f4b1454bc875b4f994e1a358796ac78b21

https://github.com/phetsims/circuit-construction-kit-common/commit/b11aeb34eeec7cf56a714474eb6d261ff6a41fee

https://github.com/phetsims/circuit-construction-kit-common/commit/1a255a938a5ddfff94c736c1de3f3e786acd7197
https://github.com/phetsims/circuit-construction-kit-common/commit/477fa0f2b76cd2b171eddafb414c2f590b8f7019

https://github.com/phetsims/circuit-construction-kit-common/commit/fd8bc3d23c1be0ca6b662d0b6e4848eea09bba72
https://github.com/phetsims/phet-io-sim-specific/commit/803edb64c72b0f33db4b21cd9befff85309324ae

https://github.com/phetsims/circuit-construction-kit-dc/commit/2cb906f5866f7a1d8d54cd85f42bf00c279c1232
https://github.com/phetsims/phet-io-sim-specific/commit/b69d67c577369748769d47968d2095e0edd19c3e

https://github.com/phetsims/phet-io-sim-specific/commit/67fb67f44e3affd9c9ab11cad8008e71daf1eff6

https://github.com/phetsims/circuit-construction-kit-common/commit/3ad9f7682d164a819dc85f996a86f2614ec216bd

https://github.com/phetsims/circuit-construction-kit-common/commit/1aa39b4946412e0332f9dfbc3294c06de4bb626d
https://github.com/phetsims/circuit-construction-kit-common/commit/a7de391c42e5081e56ab5aa7fbe4a6bc1ad3aac2

https://github.com/phetsims/phet-io-sim-specific/commit/b11125e9d79aeb64bfab5c1eaa8c43ff661c6390
https://github.com/phetsims/phet-io-sim-specific/commit/768b10ee914c1c4ecc323e1258fcd58fefa3fe76

STUDIO AUTOSELECT HOPEFULLY IN RC. Just test it.
```

**Comment by samreid** [comment] 2023-03-08 19:55
Sorted:

```
NEWEST
https://github.com/phetsims/circuit-construction-kit-common/commit/a7de391c42e5081e56ab5aa7fbe4a6bc1ad3aac2
https://github.com/phetsims/circuit-construction-kit-common/commit/477fa0f2b76cd2b171eddafb414c2f590b8f7019
https://github.com/phetsims/circuit-construction-kit-common/commit/1aa39b4946412e0332f9dfbc3294c06de4bb626d
https://github.com/phetsims/circuit-construction-kit-common/commit/3ad9f7682d164a819dc85f996a86f2614ec216bd
https://github.com/phetsims/circuit-construction-kit-common/commit/1a255a938a5ddfff94c736c1de3f3e786acd7197
https://github.com/phetsims/circuit-construction-kit-common/commit/b11aeb34eeec7cf56a714474eb6d261ff6a41fee
https://github.com/phetsims/circuit-construction-kit-common/commit/fd8bc3d23c1be0ca6b662d0b6e4848eea09bba72
OLDEST

NEWEST
https://github.com/phetsims/phet-io-sim-specific/commit/768b10ee914c1c4ecc323e1258fcd58fefa3fe76
https://github.com/phetsims/phet-io-sim-specific/commit/b11125e9d79aeb64bfab5c1eaa8c43ff661c6390
https://github.com/phetsims/phet-io-sim-specific/commit/b69d67c577369748769d47968d2095e0edd19c3e
https://github.com/phetsims/phet-io-sim-specific/commit/264769f4b1454bc875b4f994e1a358796ac78b21
https://github.com/phetsims/phet-io-sim-specific/commit/efbfbea32113677dfc6a28ee67d0134ed030fd3e
https://github.com/phetsims/phet-io-sim-specific/commit/67fb67f44e3affd9c9ab11cad8008e71daf1eff6
https://github.com/phetsims/phet-io-sim-specific/commit/803edb64c72b0f33db4b21cd9befff85309324ae
OLDEST

https://github.com/phetsims/circuit-construction-kit-dc/commit/2cb906f5866f7a1d8d54cd85f42bf00c279c1232
```

**Comment by samreid** [comment] 2023-03-08 20:09
One merge conflict, in ValueNode (related to Text.string/Text.txt change).

**Comment by samreid** [comment] 2023-03-08 21:05
RC.3 published and up for testing.

**Comment by samreid** [comment] 2023-03-09 20:35
RC.5 was verified, so I published it.  It said:

PhET-iO deploys involve a couple of extra steps after production. Please ensure the following are accomplished:
- [ ] Make sure the sim is listed in perennial/data/phet-io-api-stable if it has had a designed production release, and update the checked in API file to match the published version.
- [ ] Create an issue in the phet-io repo and assign to @kathy-phet to update the main "PhET-iO Simulations" spreadsheet from this new publication. (https://docs.google.com/spreadsheets/d/18_QNGuVtYtxOEKG9xRBs_PSQpyvzySF1Gk5puR-5Fv4/edit#gid=1881767354)

**Comment by kathy-phet** [comment] 2023-03-09 23:30
I already did the above check box. Great work all!! Amazing to have this out!

**Comment by samreid** [comment] 2023-03-11 15:12
> Make sure the sim is listed in perennial/data/phet-io-api-stable if it has had a designed production release, and update the checked in API file to match the published version.

Yes, it is listed in phet-io-api stable.  

> update the checked in API file to match the published version.

This will cause API incompatibilities. I tested this by copying https://phet-io.colorado.edu/sims/circuit-construction-kit-dc/1.3/circuit-construction-kit-dc-phet-io-api.json into master and seeing numerous differences.  @zepumph should we change the documentation about this process?

**Comment by zepumph** [comment] 2023-03-13 16:34
Ahh right. Yes, I think in general the instructions make sense, basically it is saying "we just published this API, let's see how different it is from master." In this case, we had a large reckoning in `general` while this was in RC (in https://github.com/phetsims/phet-io/issues/1913), and decided it wasn't worth maintenance releasing to CCK and Molecule Shapes. 

So all you have to do is make sure that the API is correct with master. Feel free to update the doc if it seems confusing.

**Comment by samreid** [comment] 2023-03-13 19:11
I updated the docs, @zepumph sound good?

**Closed** 2023-03-14 15:05 UTC
Labels: dev:phet-io, status:in-progress, status:ready-for-review, type:epic
